spring.application.name=student-management-backend

# Sử dụng biến môi trường linh hoạt (nếu không có biến sẽ dùng mặc định localhost)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/student_managementv1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

# Đổi validate -> update để Hibernate tự động sinh Bảng trong Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tắt Flyway nếu bạn chưa viết các file migration trong db/migration
spring.flyway.enabled=false

jwt.secret=${JWT_SECRET}

server.port=${PORT:8080}
